# The URL the site will be built for
base_url = "https://pwnwriter.github.io/wood"

#Title
title = "pwn()"
description = "I make and break softwares professionally"
author = "pwnwriter"

#favicon
favicon = "static/res/logo.png"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# When set to "true", the generated HTML files are minified.
minify_html = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# generate rss feed
feed_filename = "atom.xml"
generate_feed = true

# make lists according to assigned tags
taxonomies = [
    {name = "writings", feed = true, paginate_by = 12},
    {name = "syndicate", feed = true, paginate_by = 12},
]

# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

# Whether to set rel="nofollow" for all external links
external_links_no_follow = true

# Whether to set rel="noreferrer" for all external links
external_links_no_referrer = true

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = false
# Whether to include the path of the page/section in the index
include_path = false
# Whether to include the rendered content of the page/section in the index
include_content = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "Catppuccin-mocha"
extra_syntaxes_and_themes = ["themes"]
